### ISSUE TITLE
CPU stat issue

### ISSUE THREAD

**Issue by olsonnn** [xawen/PRTG-NetScaler#1]
Latest prtg and netscaler 11.1 
All works fine but for CPU, Packet and Management CPU, PRTG shows only 0 for all of them while this is the result i get back from the script. Really weird.... Any idea what could be wrong?

`<result>
<channel>CPU Usage</channel>
<value>0</value>
<unit>Percent</unit>
</result>
<result>
<channel>Packet CPU Usage</channel>
<value>0.400000</value>
<unit>Percent</unit>
</result>
<result>
<channel>Management CPU Usage</channel>
<value>2.800000</value>
<unit>Percent</unit>
</result>
<result>
`
Btw, thanks these great scripts!

Edit: your screenshots are showing the same issue. 0% for all 3 cpu counters

**Comment by xawen** [comment]
Good call, not sure how I missed that one.  All of the percentages (CPU and memory) were broken.  I just pushed version 1.05 with this fixed.  Thanks for the heads up!
